const fs = require('fs');

try {
    const cookiesJson = fs.readFileSync('cookies.json', 'utf8');
    const cookies = JSON.parse(cookiesJson);

    let netscapeCookies = '# Netscape HTTP Cookie File\n# This file is generated by the bot\n\n';

    cookies.forEach(cookie => {
        const domain = cookie.domain;
        const flag = cookie.hostOnly ? 'FALSE' : 'TRUE';
        const path = cookie.path;
        const secure = cookie.secure ? 'TRUE' : 'FALSE';
        const expiration = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
        const name = cookie.name;
        const value = cookie.value;

        netscapeCookies += `${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${name}\t${value}\n`;
    });

    fs.writeFileSync('cookies.txt', netscapeCookies);
    console.log('✅ Successfully converted cookies.json to cookies.txt (Netscape format)');

} catch (error) {
    console.error('❌ Error converting cookies:', error.message);
}
